declare const endPoints: {
    login: string;
    register: string;
    applicantsRegister: string;
    applicantsList: string;
    applicantDetail: string;
    applicantUpdateStatus: string;
    applicantPhoto: string;
    applicantDocument: string;
    students: string;
    studentsDeactivation: string;
    studentsActivation: string;
    createDepartmentHead: string;
    createTeacher: string;
    departmentHeads: string;
    teachers: string;
    departments: string;
    impairments: string;
    semesters: string;
    schoolBackgrounds: string;
    programModality: string;
    classYears: string;
    semester: string;
    BatchClassYearSemesters: string;
    batches: string;
    courses: string;
    regions: string;
    allWoreda: string;
    allZones: string;
    allRegion: string;
    zonesByRegion: string;
    woredasByZone: string;
    notifications: string;
    notificationsLatest: string;
    markNotificationRead: string;
    markAllNotificationsRead: string;
};
export default endPoints;
