import { jsx as _jsx } from "react/jsx-runtime";
import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import App from "./App.tsx";
import "./assets/fonts/fonts.css";
import "./index.css";
import "./lib/i18n";
import { ModalProvider } from "./hooks/Modal.tsx";
ReactDOM.createRoot(document.getElementById("root")).render(_jsx(React.StrictMode, { children: _jsx(ModalProvider, { children: _jsx(BrowserRouter, { children: _jsx(App, {}) }) }) }));
